package com.company.dlms.domain.answer;

public enum AnswerTopicFamily {
    NONE,
    ASSOCIATION_APDUS,
    ASSOCIATION_DIAGNOSTIC,
    STANDARDS_BOOK,
    PROTOCOL_HDLC_STRUCTURE,
    SECURITY_HLS,
    SECURITY_SUITE,
    SECURITY_REPLAY,
    DECODE_HDLC_U_FRAME,
    DECODE_HDLC_S_FRAME,
    DECODE_HDLC_TENTATIVE_OUTER_ROLE,
    DECODE_APDU_OPERATION,
    DECODE_AXDR_VALUE,
    DECODE_OBIS_LOOKUP,
    SICONIA_ALARM_SUMMARY,
    SICONIA_LOG_SUMMARY,
    SICONIA_XML_SUMMARY
}
